/* Generated By:JJTree&JavaCC: Do not edit this line. LogoParserConstants.java */
package com.jgrindall.logojavacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROC = 6;
  /** RegularExpression Id. */
  int END = 7;
  /** RegularExpression Id. */
  int MAKE = 8;
  /** RegularExpression Id. */
  int VARNAME = 9;
  /** RegularExpression Id. */
  int RPT = 10;
  /** RegularExpression Id. */
  int RT = 11;
  /** RegularExpression Id. */
  int FD = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int DECPOINT = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int TIMES = 17;
  /** RegularExpression Id. */
  int DIVIDE = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int LBRACKET = 21;
  /** RegularExpression Id. */
  int RBRACKET = 22;
  /** RegularExpression Id. */
  int LSQR = 23;
  /** RegularExpression Id. */
  int RSQR = 24;
  /** RegularExpression Id. */
  int NUMBER = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int ALPHA = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"proc\"",
    "\"end\"",
    "\"make\"",
    "<VARNAME>",
    "\"rpt\"",
    "\"rt\"",
    "\"fd\"",
    "<ID>",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<NUMBER>",
    "<DIGIT>",
    "<ALPHA>",
  };

}
