/* Generated By:JavaCC: Do not edit this line. LogoParserTreeConstants.java Version 5.0 */
package com.jgrindall.logojavacc;

public interface LogoParserTreeConstants
{
  public int JJTPROGRAMNODE = 0;
  public int JJTEXPRESSIONNODE = 1;
  public int JJTPLUSEXPRESSIONNODE = 2;
  public int JJTMINUSEXPRESSIONNODE = 3;
  public int JJTVOID = 4;
  public int JJTTIMESEXPRESSIONNODE = 5;
  public int JJTDIVIDEEXPRESSIONNODE = 6;
  public int JJTNEGATEEXPRESSIONNODE = 7;
  public int JJTVARIABLEVALUENODE = 8;
  public int JJTNUMBERNODE = 9;
  public int JJTFNDEFINENODE = 10;
  public int JJTVARLISTNODE = 11;
  public int JJTSTATEMENTLISTNODE = 12;
  public int JJTFNSTATEMENTLISTNODE = 13;
  public int JJTRPTSTATEMENTNODE = 14;
  public int JJTFNCALLNODE = 15;
  public int JJTEXPRESSIONLISTNODE = 16;
  public int JJTFNNAMENODE = 17;
  public int JJTFDSTATEMENTNODE = 18;
  public int JJTRTSTATEMENTNODE = 19;
  public int JJTMAKESTATEMENTNODE = 20;
  public int JJTVARIABLEDEFNNODE = 21;


  public String[] jjtNodeName = {
    "ProgramNode",
    "ExpressionNode",
    "PlusExpressionNode",
    "MinusExpressionNode",
    "void",
    "TimesExpressionNode",
    "DivideExpressionNode",
    "NegateExpressionNode",
    "VariableValueNode",
    "NumberNode",
    "FnDefineNode",
    "VarListNode",
    "StatementListNode",
    "FnStatementListNode",
    "RptStatementNode",
    "FnCallNode",
    "ExpressionListNode",
    "FnNameNode",
    "FdStatementNode",
    "RtStatementNode",
    "MakeStatementNode",
    "VariableDefnNode",
  };
}
/* JavaCC - OriginalChecksum=1ce664a89f7f99948cec1350d3c1e687 (do not edit this line) */
